#!/bin/sh /etc/rc.common

START=99
STOP=20

. /etc/profile.d/opkg.sh

start() {
	# auto(re)install user packages
	if [ ! -f "/rootfs.done" ]; then
		echo "Auto(re)install user packages"
		sleep 10s
		opkg update
		opkg_restore
		if [ -f "/rootfs.ready" ]; then
			touch "/rootfs.done"
			# add a reboot : needed for wifi activation
			sync
			reboot
		fi
 	fi
 }

stop() {
	echo "Backup user packages list"
	if [ -f "/rootfs.done" ]; then
		echo "Auto(pre)install user packages"
		opkg_backup
##		rm "/rootfs.done"
	fi
}

boot () {
	start
}
